// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reating_proto/reating.proto

package reating

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyReating struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReating) Reset()         { *m = EmptyReating{} }
func (m *EmptyReating) String() string { return proto.CompactTextString(m) }
func (*EmptyReating) ProtoMessage()    {}
func (*EmptyReating) Descriptor() ([]byte, []int) {
	return fileDescriptor_031f5aef0e75e290, []int{0}
}
func (m *EmptyReating) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmptyReating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmptyReating.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmptyReating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReating.Merge(m, src)
}
func (m *EmptyReating) XXX_Size() int {
	return m.Size()
}
func (m *EmptyReating) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReating.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReating proto.InternalMessageInfo

type ReatingForCreate struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id"`
	CustumerId           int64    `protobuf:"varint,2,opt,name=custumer_id,json=custumerId,proto3" json:"custumer_id"`
	Reating              int64    `protobuf:"varint,3,opt,name=reating,proto3" json:"reating"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReatingForCreate) Reset()         { *m = ReatingForCreate{} }
func (m *ReatingForCreate) String() string { return proto.CompactTextString(m) }
func (*ReatingForCreate) ProtoMessage()    {}
func (*ReatingForCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_031f5aef0e75e290, []int{1}
}
func (m *ReatingForCreate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReatingForCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReatingForCreate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReatingForCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReatingForCreate.Merge(m, src)
}
func (m *ReatingForCreate) XXX_Size() int {
	return m.Size()
}
func (m *ReatingForCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReatingForCreate.DiscardUnknown(m)
}

var xxx_messageInfo_ReatingForCreate proto.InternalMessageInfo

func (m *ReatingForCreate) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *ReatingForCreate) GetCustumerId() int64 {
	if m != nil {
		return m.CustumerId
	}
	return 0
}

func (m *ReatingForCreate) GetReating() int64 {
	if m != nil {
		return m.Reating
	}
	return 0
}

func (m *ReatingForCreate) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Reatings struct {
	Reatins              []*ReatingInfo `protobuf:"bytes,1,rep,name=reatins,proto3" json:"reatins"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Reatings) Reset()         { *m = Reatings{} }
func (m *Reatings) String() string { return proto.CompactTextString(m) }
func (*Reatings) ProtoMessage()    {}
func (*Reatings) Descriptor() ([]byte, []int) {
	return fileDescriptor_031f5aef0e75e290, []int{2}
}
func (m *Reatings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Reatings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Reatings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Reatings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reatings.Merge(m, src)
}
func (m *Reatings) XXX_Size() int {
	return m.Size()
}
func (m *Reatings) XXX_DiscardUnknown() {
	xxx_messageInfo_Reatings.DiscardUnknown(m)
}

var xxx_messageInfo_Reatings proto.InternalMessageInfo

func (m *Reatings) GetReatins() []*ReatingInfo {
	if m != nil {
		return m.Reatins
	}
	return nil
}

type Id struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_031f5aef0e75e290, []int{3}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Id.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return m.Size()
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReatingInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	PostId               int64    `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id"`
	CustumerId           int64    `protobuf:"varint,3,opt,name=custumer_id,json=custumerId,proto3" json:"custumer_id"`
	Reating              int64    `protobuf:"varint,4,opt,name=reating,proto3" json:"reating"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReatingInfo) Reset()         { *m = ReatingInfo{} }
func (m *ReatingInfo) String() string { return proto.CompactTextString(m) }
func (*ReatingInfo) ProtoMessage()    {}
func (*ReatingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_031f5aef0e75e290, []int{4}
}
func (m *ReatingInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReatingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReatingInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReatingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReatingInfo.Merge(m, src)
}
func (m *ReatingInfo) XXX_Size() int {
	return m.Size()
}
func (m *ReatingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReatingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReatingInfo proto.InternalMessageInfo

func (m *ReatingInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReatingInfo) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *ReatingInfo) GetCustumerId() int64 {
	if m != nil {
		return m.CustumerId
	}
	return 0
}

func (m *ReatingInfo) GetReating() int64 {
	if m != nil {
		return m.Reating
	}
	return 0
}

func (m *ReatingInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyReating)(nil), "reating.EmptyReating")
	proto.RegisterType((*ReatingForCreate)(nil), "reating.ReatingForCreate")
	proto.RegisterType((*Reatings)(nil), "reating.Reatings")
	proto.RegisterType((*Id)(nil), "reating.Id")
	proto.RegisterType((*ReatingInfo)(nil), "reating.ReatingInfo")
}

func init() { proto.RegisterFile("reating_proto/reating.proto", fileDescriptor_031f5aef0e75e290) }

var fileDescriptor_031f5aef0e75e290 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xfd, 0x66, 0xd2, 0xa6, 0x9f, 0x37, 0x12, 0xea, 0x50, 0x31, 0x56, 0x88, 0x21, 0xab, 0x82,
	0xd0, 0x4a, 0x75, 0xa3, 0x4b, 0xff, 0x4a, 0x76, 0x52, 0x71, 0x5d, 0xb4, 0x33, 0xca, 0x80, 0xed,
	0x84, 0x99, 0xa9, 0xe0, 0x1b, 0xb8, 0x15, 0x37, 0x3e, 0x92, 0x4b, 0x1f, 0x41, 0xea, 0x8b, 0x48,
	0xc2, 0x4c, 0x88, 0x35, 0x66, 0x97, 0x73, 0xcf, 0x99, 0x7b, 0xcf, 0xb9, 0xb9, 0xb0, 0x23, 0xd9,
	0x8d, 0xe6, 0xf3, 0xfb, 0x49, 0x2a, 0x85, 0x16, 0x03, 0x83, 0xfa, 0x39, 0x22, 0x2d, 0x03, 0x63,
	0x1f, 0xd6, 0xcf, 0x67, 0xa9, 0x7e, 0x1a, 0x1b, 0xfc, 0x8c, 0xa0, 0x6d, 0xbe, 0x2f, 0x84, 0x3c,
	0xcd, 0x64, 0x8c, 0x6c, 0x41, 0x2b, 0x15, 0x4a, 0x4f, 0x38, 0x0d, 0x50, 0x84, 0x7a, 0xce, 0xd8,
	0xcd, 0x60, 0x42, 0xc9, 0x2e, 0x78, 0xd3, 0x85, 0xd2, 0x8b, 0x19, 0x93, 0x19, 0x89, 0x73, 0x12,
	0x6c, 0x29, 0xa1, 0x24, 0x00, 0x3b, 0x29, 0x70, 0x72, 0xd2, 0x42, 0x12, 0x81, 0x47, 0x99, 0x9a,
	0x4a, 0x9e, 0x6a, 0x2e, 0xe6, 0x41, 0x23, 0x42, 0xbd, 0xb5, 0x71, 0xb9, 0x14, 0x1f, 0xc3, 0x7f,
	0xe3, 0x44, 0x91, 0xbe, 0xed, 0xa3, 0x02, 0x14, 0x39, 0x3d, 0x6f, 0xd8, 0xe9, 0xdb, 0x40, 0x46,
	0x93, 0xcc, 0xef, 0x84, 0xed, 0xae, 0xe2, 0x0e, 0xe0, 0x84, 0x12, 0x1f, 0x70, 0x61, 0x19, 0x73,
	0x1a, 0xbf, 0x22, 0xf0, 0x4a, 0xf2, 0x55, 0xbe, 0x9c, 0x13, 0xd7, 0xe5, 0x74, 0xea, 0x72, 0x36,
	0x6a, 0x73, 0x36, 0x7f, 0xe5, 0x1c, 0xbe, 0x60, 0xf0, 0x8d, 0xab, 0x2b, 0x26, 0x1f, 0xf9, 0x94,
	0x91, 0x23, 0x70, 0xcd, 0xea, 0xb7, 0x57, 0x73, 0x16, 0x7f, 0xa5, 0x5b, 0xb9, 0x02, 0xb2, 0x0f,
	0xfe, 0x88, 0xe9, 0x4b, 0xa1, 0xb4, 0xa9, 0x12, 0xaf, 0xd0, 0x25, 0xb4, 0xbb, 0xb1, 0xfa, 0x48,
	0x91, 0x01, 0xc0, 0x88, 0x55, 0xab, 0xab, 0x47, 0x1c, 0x82, 0x7b, 0x9d, 0xd2, 0xcc, 0x5d, 0x25,
	0xff, 0xc7, 0xab, 0x3d, 0x68, 0x9e, 0xb1, 0x07, 0xa6, 0x7f, 0x4e, 0xd8, 0x2c, 0x40, 0xf9, 0x0c,
	0x4f, 0xda, 0xef, 0xcb, 0x10, 0x7d, 0x2c, 0x43, 0xf4, 0xb9, 0x0c, 0xd1, 0xdb, 0x57, 0xf8, 0xef,
	0xd6, 0xcd, 0x0f, 0xf7, 0xe0, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xa7, 0xaa, 0x4c, 0xd7, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReatingServiceClient is the client API for ReatingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReatingServiceClient interface {
	Create(ctx context.Context, in *ReatingForCreate, opts ...grpc.CallOption) (*ReatingInfo, error)
	GetPostReating(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Reatings, error)
	GetReating(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ReatingInfo, error)
	Update(ctx context.Context, in *ReatingInfo, opts ...grpc.CallOption) (*ReatingInfo, error)
	Delet(ctx context.Context, in *Id, opts ...grpc.CallOption) (*EmptyReating, error)
}

type reatingServiceClient struct {
	cc *grpc.ClientConn
}

func NewReatingServiceClient(cc *grpc.ClientConn) ReatingServiceClient {
	return &reatingServiceClient{cc}
}

func (c *reatingServiceClient) Create(ctx context.Context, in *ReatingForCreate, opts ...grpc.CallOption) (*ReatingInfo, error) {
	out := new(ReatingInfo)
	err := c.cc.Invoke(ctx, "/reating.ReatingService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reatingServiceClient) GetPostReating(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Reatings, error) {
	out := new(Reatings)
	err := c.cc.Invoke(ctx, "/reating.ReatingService/GetPostReating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reatingServiceClient) GetReating(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ReatingInfo, error) {
	out := new(ReatingInfo)
	err := c.cc.Invoke(ctx, "/reating.ReatingService/GetReating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reatingServiceClient) Update(ctx context.Context, in *ReatingInfo, opts ...grpc.CallOption) (*ReatingInfo, error) {
	out := new(ReatingInfo)
	err := c.cc.Invoke(ctx, "/reating.ReatingService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reatingServiceClient) Delet(ctx context.Context, in *Id, opts ...grpc.CallOption) (*EmptyReating, error) {
	out := new(EmptyReating)
	err := c.cc.Invoke(ctx, "/reating.ReatingService/Delet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReatingServiceServer is the server API for ReatingService service.
type ReatingServiceServer interface {
	Create(context.Context, *ReatingForCreate) (*ReatingInfo, error)
	GetPostReating(context.Context, *Id) (*Reatings, error)
	GetReating(context.Context, *Id) (*ReatingInfo, error)
	Update(context.Context, *ReatingInfo) (*ReatingInfo, error)
	Delet(context.Context, *Id) (*EmptyReating, error)
}

// UnimplementedReatingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReatingServiceServer struct {
}

func (*UnimplementedReatingServiceServer) Create(ctx context.Context, req *ReatingForCreate) (*ReatingInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedReatingServiceServer) GetPostReating(ctx context.Context, req *Id) (*Reatings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostReating not implemented")
}
func (*UnimplementedReatingServiceServer) GetReating(ctx context.Context, req *Id) (*ReatingInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReating not implemented")
}
func (*UnimplementedReatingServiceServer) Update(ctx context.Context, req *ReatingInfo) (*ReatingInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedReatingServiceServer) Delet(ctx context.Context, req *Id) (*EmptyReating, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delet not implemented")
}

func RegisterReatingServiceServer(s *grpc.Server, srv ReatingServiceServer) {
	s.RegisterService(&_ReatingService_serviceDesc, srv)
}

func _ReatingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReatingForCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReatingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reating.ReatingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReatingServiceServer).Create(ctx, req.(*ReatingForCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReatingService_GetPostReating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReatingServiceServer).GetPostReating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reating.ReatingService/GetPostReating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReatingServiceServer).GetPostReating(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReatingService_GetReating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReatingServiceServer).GetReating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reating.ReatingService/GetReating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReatingServiceServer).GetReating(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReatingService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReatingInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReatingServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reating.ReatingService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReatingServiceServer).Update(ctx, req.(*ReatingInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReatingService_Delet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReatingServiceServer).Delet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reating.ReatingService/Delet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReatingServiceServer).Delet(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReatingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reating.ReatingService",
	HandlerType: (*ReatingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ReatingService_Create_Handler,
		},
		{
			MethodName: "GetPostReating",
			Handler:    _ReatingService_GetPostReating_Handler,
		},
		{
			MethodName: "GetReating",
			Handler:    _ReatingService_GetReating_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ReatingService_Update_Handler,
		},
		{
			MethodName: "Delet",
			Handler:    _ReatingService_Delet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reating_proto/reating.proto",
}

func (m *EmptyReating) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmptyReating) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmptyReating) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *ReatingForCreate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReatingForCreate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReatingForCreate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintReating(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if m.Reating != 0 {
		i = encodeVarintReating(dAtA, i, uint64(m.Reating))
		i--
		dAtA[i] = 0x18
	}
	if m.CustumerId != 0 {
		i = encodeVarintReating(dAtA, i, uint64(m.CustumerId))
		i--
		dAtA[i] = 0x10
	}
	if m.PostId != 0 {
		i = encodeVarintReating(dAtA, i, uint64(m.PostId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Reatings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Reatings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Reatings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Reatins) > 0 {
		for iNdEx := len(m.Reatins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reatins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintReating(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Id) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Id) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Id) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Id != 0 {
		i = encodeVarintReating(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReatingInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReatingInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReatingInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintReating(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Reating != 0 {
		i = encodeVarintReating(dAtA, i, uint64(m.Reating))
		i--
		dAtA[i] = 0x20
	}
	if m.CustumerId != 0 {
		i = encodeVarintReating(dAtA, i, uint64(m.CustumerId))
		i--
		dAtA[i] = 0x18
	}
	if m.PostId != 0 {
		i = encodeVarintReating(dAtA, i, uint64(m.PostId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintReating(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintReating(dAtA []byte, offset int, v uint64) int {
	offset -= sovReating(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EmptyReating) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReatingForCreate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PostId != 0 {
		n += 1 + sovReating(uint64(m.PostId))
	}
	if m.CustumerId != 0 {
		n += 1 + sovReating(uint64(m.CustumerId))
	}
	if m.Reating != 0 {
		n += 1 + sovReating(uint64(m.Reating))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovReating(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Reatings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Reatins) > 0 {
		for _, e := range m.Reatins {
			l = e.Size()
			n += 1 + l + sovReating(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Id) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovReating(uint64(m.Id))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReatingInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovReating(uint64(m.Id))
	}
	if m.PostId != 0 {
		n += 1 + sovReating(uint64(m.PostId))
	}
	if m.CustumerId != 0 {
		n += 1 + sovReating(uint64(m.CustumerId))
	}
	if m.Reating != 0 {
		n += 1 + sovReating(uint64(m.Reating))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovReating(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovReating(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReating(x uint64) (n int) {
	return sovReating(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EmptyReating) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmptyReating: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmptyReating: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipReating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReatingForCreate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReatingForCreate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReatingForCreate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostId", wireType)
			}
			m.PostId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PostId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustumerId", wireType)
			}
			m.CustumerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CustumerId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reating", wireType)
			}
			m.Reating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reating |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Reatings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Reatings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Reatings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reatins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reatins = append(m.Reatins, &ReatingInfo{})
			if err := m.Reatins[len(m.Reatins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Id) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Id: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Id: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReatingInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReatingInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReatingInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostId", wireType)
			}
			m.PostId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PostId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustumerId", wireType)
			}
			m.CustumerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CustumerId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reating", wireType)
			}
			m.Reating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reating |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReating(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReating
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReating
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReating
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReating
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReating
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReating
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReating        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReating          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReating = fmt.Errorf("proto: unexpected end of group")
)
